apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-pingdom-exporter.fullname" . }}
  labels:
    {{- include "prometheus-pingdom-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-pingdom-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.pod.annotations }}
      annotations:
        {{- toYaml .Values.pod.annotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-pingdom-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WAIT_SECONDS
              value: {{ .Values.waitSeconds }}
            - name: PORT
              value: {{ .Values.service.port }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "prometheus-pingdom-exporter.secret.name" . }}
                  key: {{ include "prometheus-pingdom-exporter.secret.key" . }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}