{{- if .Values.monitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-prometheus-pingdom-exporter
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: prometheus-pingdom-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: prometheus-pingdom-exporter
  endpoints:
    - port: http
      interval: 1m
{{- end -}}