apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-pingdom-exporter
  labels:
    {{- toYaml ".Values.labels" | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml ".Values.selectorLabels" | nindent 4 }}