apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-pingdom-exporter
  labels:
    app: prometheus-pingdom-exporter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: prometheus-pingdom-exporter
